name: Print message
on:
   push: 
     branches: master
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Message
          run: echo "Message"
  alert:
      runs-on: ubuntu-latest
      if: always()
      steps:
        - name: Send mail
          run: mail -s "CI/CD Status" megharajmathur0224@gmail.com
